Repository gazbert/bxbot, pull requests merged in 2021-01, with the labels that each got.

#128 Dependency updates
  README.md
  build.gradle
  bxbot-core/src/main/resources/banner.txt
  bxbot-rest-api/src/main/resources/banner.txt
  bxbot.bat
  bxbot.sh
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  pom.xml
Labels: dependencies

#129 Issue-127 :
  bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/KrakenExchangeAdapter.java
Labels: bug

#131 KrakenAdaptor place order with expected precision
  bxbot-exchange-api/src/main/java/com/gazbert/bxbot/exchange/api/PairPrecisionConfig.java
  bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/KrakenExchangeAdapter.java
  bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/config/PairPrecisionConfigImpl.java
  bxbot-exchanges/src/test/exchange-data/kraken/AssetPairs.json
  bxbot-exchanges/src/test/java/com/gazbert/bxbot/exchanges/TestKrakenExchangeAdapter.java
Labels: bug

#133 Merge David Huertas Coinbase Pro exchange adapter work into new coinbase-pro feature branch
  bxbot-exchanges/src/main/java/com/gazbert/bxbot/exchanges/CoinbaseProExchangeAdapter.java
  bxbot-exchanges/src/test/exchange-data/coinbasepro/accounts.json
  bxbot-exchanges/src/test/exchange-data/coinbasepro/book.json
  bxbot-exchanges/src/test/exchange-data/coinbasepro/cancel.json
  bxbot-exchanges/src/test/exchange-data/coinbasepro/new_buy_order.json
  bxbot-exchanges/src/test/exchange-data/coinbasepro/new_sell_order.json
  bxbot-exchanges/src/test/exchange-data/coinbasepro/orders.json
  bxbot-exchanges/src/test/exchange-data/coinbasepro/stats.json
  bxbot-exchanges/src/test/exchange-data/coinbasepro/ticker.json
  bxbot-exchanges/src/test/java/com/gazbert/bxbot/exchanges/TestCoinbaseProExchangeAdapter.java
Labels: enhancement
